In [13]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
import pandas as pd


from skimage.morphology import watershed
from skimage.feature import peak_local_max
from PIL import Image

from skimage.morphology import skeletonize, thin, skeletonize_3d
from skimage.util import invert
from skimage import measure
from skimage.morphology import erosion, dilation, opening, closing, white_tophat
from skimage.morphology import black_tophat, skeletonize, convex_hull_image
from skimage.morphology import disk
from skimage import feature
from skimage.filters import roberts, sobel, scharr, prewitt
import seaborn as sns
sns.reset_orig()

from skimage import restoration

from skimage import exposure
from skimage.filters import gaussian

from scipy import ndimage

from time import time

from skimage.color import rgb2gray


from skimage.filters.rank import entropy
import scipy



import networkx as nx
from scipy import interpolate

from skimage.segmentation import random_walker
from skimage.data import binary_blobs
from skimage.exposure import rescale_intensity
import glob

from skimage.morphology import disk
from skimage import io
from skimage.morphology import remove_small_objects

import threading


import tifffile

/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning:
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)

In [14]:
def Node_Seg_matching(arr, mask):
    
    arr2 = (arr.copy())*0
    
    
    #IN YZ PLANE
    
    #bottom front
    arr2[:-1,:-1] += arr[1:,1:]
    #bottom 
    arr2[:-1] += arr[1:]
    #bottom back
    arr2[:-1, 1:] += arr[1:, :-1]
    
    #top front
    arr2[1:, :-1] += arr[:-1, 1:]
    #top
    arr2[1:] += arr[:-1]
    #top back
    arr2[1:, 1:] += arr[:-1, :-1]
    
    #front
    arr2[:, :-1] += arr[:, 1:]
    #back
    arr2[:, 1:] += arr[:, :-1]
    
    
    
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT 
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT
    
    #bottom front
    arr2[:-1,:-1, 1:] += arr[1:,1:, :-1]
    #bottom 
    arr2[:-1, :, 1:] += arr[1:, :, :-1]
    #bottom back
    arr2[:-1, 1:, 1:] += arr[1:, :-1, :-1]
    
    #top front
    arr2[1:, :-1, 1:] += arr[:-1, 1:, :-1]
    #top
    arr2[1:, :, 1:] += arr[:-1, :, :-1]
    #top back
    arr2[1:, 1:, 1:] += arr[:-1, :-1, :-1]
    
    #front
    arr2[:, :-1, 1:] += arr[:, 1:, :-1]
    #back
    arr2[:, 1:, 1:] += arr[:, :-1, :-1]
    
    #just left 
    arr2[:, :, 1:] += arr[:, :, :-1]
    
    
    
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    
    #bottom front
    arr2[:-1,:-1, :-1] += arr[1:,1:, 1:]
    #bottom 
    arr2[:-1, :, :-1] += arr[1:, :, 1:]
    #bottom back
    arr2[:-1, 1:, :-1] += arr[1:, :-1, 1:]
    
    #top front
    arr2[1:, :-1, :-1] += arr[:-1, 1:, 1:]
    #top
    arr2[1:, :, :-1] += arr[:-1, :, 1:]
    #top back
    arr2[1:, 1:, :-1] += arr[:-1, :-1, 1:]
    
    #front
    arr2[:, :-1, :-1] += arr[:, 1:, 1:]
    #back
    arr2[:, 1:, :-1] += arr[:, :-1, 1:]
    
    
    #just right 
    arr2[:, :, :-1] += arr[:, :, 1:]
    
    
    
    return arr2*(mask!=0)

In [15]:
def getNeighbors(arr):
    
    arr2 = (arr.copy())*0
    
    
    #IN YZ PLANE
    
    #bottom front
    arr2[:-1,:-1] += arr[1:,1:]
    #bottom 
    arr2[:-1] += arr[1:]
    #bottom back
    arr2[:-1, 1:] += arr[1:, :-1]
    
    #top front
    arr2[1:, :-1] += arr[:-1, 1:]
    #top
    arr2[1:] += arr[:-1]
    #top back
    arr2[1:, 1:] += arr[:-1, :-1]
    
    #front
    arr2[:, :-1] += arr[:, 1:]
    #back
    arr2[:, 1:] += arr[:, :-1]
    
    
    
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT 
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT
    #LEFT LEFT LEFT LEFT LEFT LEFT LEFT
    
    #bottom front
    arr2[:-1,:-1, 1:] += arr[1:,1:, :-1]
    #bottom 
    arr2[:-1, :, 1:] += arr[1:, :, :-1]
    #bottom back
    arr2[:-1, 1:, 1:] += arr[1:, :-1, :-1]
    
    #top front
    arr2[1:, :-1, 1:] += arr[:-1, 1:, :-1]
    #top
    arr2[1:, :, 1:] += arr[:-1, :, :-1]
    #top back
    arr2[1:, 1:, 1:] += arr[:-1, :-1, :-1]
    
    #front
    arr2[:, :-1, 1:] += arr[:, 1:, :-1]
    #back
    arr2[:, 1:, 1:] += arr[:, :-1, :-1]
    
    #just left 
    arr2[:, :, 1:] += arr[:, :, :-1]
    
    
    
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    #RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT
    
    #bottom front
    arr2[:-1,:-1, :-1] += arr[1:,1:, 1:]
    #bottom 
    arr2[:-1, :, :-1] += arr[1:, :, 1:]
    #bottom back
    arr2[:-1, 1:, :-1] += arr[1:, :-1, 1:]
    
    #top front
    arr2[1:, :-1, :-1] += arr[:-1, 1:, 1:]
    #top
    arr2[1:, :, :-1] += arr[:-1, :, 1:]
    #top back
    arr2[1:, 1:, :-1] += arr[:-1, :-1, 1:]
    
    #front
    arr2[:, :-1, :-1] += arr[:, 1:, 1:]
    #back
    arr2[:, 1:, :-1] += arr[:, :-1, 1:]
    
    
    #just right 
    arr2[:, :, :-1] += arr[:, :, 1:]
    
    
    
    return arr2*(arr!=0)

In [16]:
segs = io.imread("/Users/spencerlab/Downloads/skel_Segs.tif")
nodes = io.imread("/Users/spencerlab/Downloads/skel_Nodes.tif")

In [17]:
segs = segs*(getNeighbors(segs!=0)>0) # gets rid of all single pixel segments

In [18]:
# labels segs & nodes
labeled_nodes,num_nodes = ndi.measurements.label(nodes, np.ones((3,3,3)))
labeled_segs, num_segs = ndi.measurements.label(segs, np.ones((3,3,3)))

In [19]:
# all endpoints
endpoints = getNeighbors(segs!=0) == 1

In [20]:
# endpoints w node label
labeled_endpoints = Node_Seg_matching(labeled_nodes,endpoints)

In [21]:
all_endpt_loc = np.where(endpoints!=0)

In [22]:
from datetime import datetime

In [23]:
all_segs = np.full((num_segs+1, 9), -1)

print(datetime.now())

for i in range(len(all_endpt_loc[0])): # iterates through each endpoint location
    z = (all_endpt_loc[0][i])
    y = (all_endpt_loc[1][i])
    x = (all_endpt_loc[2][i])
    
    seg_label = labeled_segs[z,y,x] 
    node_label = labeled_endpoints[z,y,x] 
    
    
    if(all_segs[seg_label][0] == -1):
        all_segs[seg_label][0] = seg_label
        all_segs[seg_label][1] = z
        all_segs[seg_label][2] = y
        all_segs[seg_label][3] = x
        all_segs[seg_label][4] = node_label

    else:
        all_segs[seg_label][5] = z
        all_segs[seg_label][6] = y
        all_segs[seg_label][7] = x
        all_segs[seg_label][8] = node_label
        
print(datetime.now())

2020-09-12 13:42:02.287194
2020-09-12 13:42:04.424172

In [22]:
all_segs

array([[    -1,     -1,     -1, ...,     -1,     -1,     -1],
       [     1,      0,    618, ...,    620,   1351,    350],
       [     2,      0,    625, ...,    624,   1407,      0],
       ...,
       [365141,    273,   2115, ...,   2121,   2988, 222000],
       [365142,    273,   2122, ...,   2123,   2883, 221868],
       [365143,    273,   2124, ...,   2125,   2811, 221974]])

In [24]:
df = pd.DataFrame(all_segs, columns = ['Segment Label', 'Z1', 'Y1', 'X1', "Node 1 Label", 'Z2', 'Y2', 'X2', "Node 2 Label" ])

In [58]:
# df
df.iloc[20:50, :]

    Segment Label  Z1   Y1    X1  Node 1 Label  Z2   Y2    X2  Node 2 Label
20             20   0  638  1458            10   0  687  1522             0
21             21   0  639  1421            12   0  639  1424             0
22             22   0  640  1346            11   0  644  1333            13
23             23   0  640  1418            12   0  642  1413             0
24             24   0  643  1401             0   0  643  1402             0
25             25   0  647  1331            13   0  650  1330           194
26             26   0  665  1323            14   1  652  1328           194
27             27   1  685  1316           195   1  692  1313           196
28             28   0  696  1525             0   0  702  1527            15
29             29   0  703  1522             0   0  703  1525            15
30             30   0  704  1527            15   0  769  1536           199
31             31   0  705  1300            16   2  698  1311           422
32             32   0  707  1298            16   0  716  1290            17
33             33   0  717  1292            17   1  716  1298           197
34             34   0  718  1290            17   0  719  1289            18
35             35   0  720  1291            18   2  721  1297           423
36             36   0  723  1288            19   0  738  1280            20
37             37   0  723  1290            19   0  726  1300           198
38             38   0  726  1311             0   0  727  1311             0
39             39   0  741  1279            20   0  745  1276            21
40             40   0  746  1284             0   1  741  1281            20
41             41   0  749  1272            22   0  756  1271            23
42             42   0  759  1271            23   0  774  1270            24
43             43   0  771  1536           199   2  784  1533           201
44             44   0  775  1267            24   1  772  1261           427
45             45   0  778  1267            25   1  778  1263           428
46             46   0  779  1269            25   0  783  1265            27
47             47   1  780  1258           200   5  792  1261          1072
48             48   0  783  1261            26   3  782  1262           428
49             49   0  785  1264            27   0  787  1263            28

In [26]:
#  FINAL CSV
df.to_csv("/Users/spencerlab/Downloads/thymus2/seg_nodes_2.csv")

In [60]:
node1 = np.asarray(df["Node 1 Label"])

In [61]:
wh = np.where(node1==0)

In [62]:
len(wh[0])

41693

In [64]:
len(wh[0])/len(node1)

0.11418234997699538

In [ ]:
#  FINAL CSV

In [186]:
from datetime import datetime

In [46]:
# all_segs = []

print(datetime.now())

i = 4

each_seg = []
each_seg.append(i)
endpt_loc = np.where(endpoints_of_all_seg == i)


for k in range(2):
    z = (endpt_loc[0][k])
    y = (endpt_loc[1][k])
    x = (endpt_loc[2][k])

    each_seg.append(z)
    each_seg.append(y)
    each_seg.append(x)

    each_seg.append(labeled_endpoints[z,y,x])

#     all_segs.append(each_seg)

# print(datetime.now())

2020-09-08 16:29:23.943076

In [47]:
each_seg

[4, 0, 626, 1407, 0, 0, 629, 1406, 0]